version: '3'
services:
  web:
    build:
      context: app

    stop_signal: SIGINT
    ports:
      - '1235:8000'
    volumes:
      - './app:/app'
    networks:
      - valhalla

networks:
  valhalla:
    external: true
